### ISSUE TITLE
wrong use of query ids

### ISSUE THREAD

**Issue by laura-dietz** [gauravpatil93/evalutation-framework#2]
In EF_Results.py  You are misusing the query ID to produce text.
```
def get_query_plan_text(self):
        query = self.query_text
        query = re.sub('%20', ' ', query)
return query
```

This is really only intended to be used as a unique query identifier

Various kinds of non-ascii characters are replaces - not just spaces. 

You should get the words for a query from one of the other entries of the CBOR. Use the trec-car-tools for accessing the content of the CBOR files.

**Comment by gauravpatil93** [comment]
I have removed the functions from the classes. I tried the tool and yes that makes more sense to me now.
